### ISSUE TITLE
Immutable Style classes not found

### ISSUE THREAD

**Issue by wenhoujx** [palantir/tracing-java#178]
## What happened?
when add benchmark on span in https://github.com/palantir/tracing-java/pull/176  and run `./gradlew jmh` 
```
> Task :tracing-benchmarks:compileJmhJava FAILED
warning: unknown enum constant ImplementationVisibility.PACKAGE
  reason: class file for org.immutables.value.Value$Style$ImplementationVisibility not found
error: warnings found and -Werror specified
1 error
1 warning

```
This is because the tracing-api module uses @Immutables but does not include the annotations as compile time dependencies (it cannot find the styles classes). This causes downstream java warnings., forcing downstream consuming project add annotations in their compile classpath. 

Two possible solutions would be to:

include the annotations in the classpath:

1. compile group: 'org.immutables', name: 'value', classifier: 'annotations'

2. create and switch to an annotation provided in the auth-tokens module itself (i.e. something named @ImmutableStyles)

see similar issues in other palantir projects: 
https://github.com/palantir/auth-tokens/issues/28 
https://github.com/palantir/dropwizard-web-security/issues/54

solution suggested by immutables author: 
https://github.com/immutables/immutables/issues/291#issuecomment-213574619

**Comment by carterkozak** [comment]
This sounds like an issue with a PR that hasn't merged

**Comment by carterkozak** [comment]
We don't want to ship the immutables annotations because they're only used at compile time. Dependent modules may also need a compile-time dependency on these annotations.

**Comment by wenhoujx** [comment]
if we use the custom annotation, dependent modules does not need a compile-time dep.

**Comment by carterkozak** [comment]
Except on that annotation, unless it's a compileOnly dependency from another module. I don't think this makes a difference outside of modules from the same codebase, so I'm not sure it's worth changing much code to support it.

**Comment by schlosna** [comment]
https://github.com/palantir/tracing-java/blob/a86e0023bd5327a02518743b3ad11e91d248a955/build.gradle#L69 in #176 promotes all warnings to errors. We can take that out, but generally I'd like to find a way to get the immutables generated JSON classes to place nice with `-Werror`. I've hit similar issues in tritium in the past and have not been able to force warnings to be treated as errors due to this.

**Comment by carterkozak** [comment]
Does a compileOnly dep on immutables annotations in the jmh module resolve the warning?

**Comment by wenhoujx** [comment]
@carterkozak nope, tried `compileOnly`, doesn't work, `compile` works. :(
