### ISSUE TITLE
It should be possible to remove a span from stack and complete it asynchronously

### ISSUE THREAD

**Issue by robert3005** [palantir/tracing-java#316]
## What happened?

I am using an interface generated by conjure-java retrofit generator which returns ListenableFuture. What I would like to achieve is being able to parent all work being done to return the listenable future in a span but would like to complete that span only when the future actually completes. Right now I can add a wrapping span that's a sibling to the async spans via DetachedSpan.start and I can add a wrapping span that's a parent that would complete as soon as the synchronous part of the work is done. I believe the issue is that I can only transition from an async to synchronous span (via completeAndStartChild) but I can never convert a synchronous span to async one.

## What did you want to happen?

Not sure what's the best api here but the ask is to effectively be able to detach an existing span and complete it elsewhere. This would let me achieve workflow above by starting a span, making a call, getting result back and detaching a span, registering a callback that closes the span.

**Comment by carterkozak** [comment]
Would something like this work?

```java
DetachedSpan detached = DetachedSpan.start("retrofit-parent");
ListenableFuture<String> result = FluentFuture.from(retrofitClient.greeting())
    .transformAsync(<args>) // any work you need to associate with the future
    .addListener(detached::complete, MoreExecutors.directExecutor());
```

**Comment by carterkozak** [comment]
To make sure I'm following correctly, are you writing this as a conjure-java-runtime feature, or in application code?

**Comment by robert3005** [comment]
so this is library code on top of a conjure retrofit client. The annoying thing with your suggestion is that it's a sibling of all the traces that conjure creates leading to confusing traces

**Comment by carterkozak** [comment]
How about something like this? https://github.com/palantir/tracing-java/pull/323#discussion_r336613094

It avoids the sibling problem, but nests the initial request creation one layer deeper.

**Comment by robert3005** [comment]
#328 provides the necessary functionality - I missed that case before
