### ISSUE TITLE
Call to wrapWithNewTrace incorrectly restores state if there is no current trace

### ISSUE THREAD

**Issue by dsd987** [palantir/tracing-java#51]
## What happened?
Calling Tracers.wrapWithNewTrace when no trace is currently set will result in a new trace being restored on completion rather than a cleared trace state.

## What did you want to happen?
The trace state should be restored back to the same state as before the call was made, so in this case, a cleared trace state.

**Comment by carterkozak** [comment]
Fixed in 2.1.1
